// LLM Usage Level: Assistant

#include "../include/skald_emit.h"
#include "skald_version.h"
#include <cmath>
#include <cstdio>

namespace Skald::Emit {

namespace {

void indent(std::string &out, int depth) {
  out.append(static_cast<size_t>(depth) * 2, ' ');
}

void write_string(std::string &out, const std::string &s) {
  out += '"';
  for (unsigned char c : s) {
    switch (c) {
    case '\\':
      out += "\\\\";
      break;
    case '"':
      out += "\\\"";
      break;
    case '\n':
      out += "\\n";
      break;
    case '\r':
      out += "\\r";
      break;
    case '\t':
      out += "\\t";
      break;
    default:
      if (c < 0x20 || c == 0x7f) {
        char buf[8];
        std::snprintf(buf, sizeof buf, "\\%03u", c);
        out += buf;
      } else {
        out += static_cast<char>(c);
      }
    }
  }
  out += '"';
}

void write_float(std::string &out, double d) {
  if (std::isnan(d)) {
    out += "(0/0)";
    return;
  }
  if (std::isinf(d)) {
    out += d < 0 ? "-math.huge" : "math.huge";
    return;
  }
  char buf[32];
  std::snprintf(buf, sizeof buf, "%.9g", d);
  std::string s = buf;
  if (s.find('.') == std::string::npos && s.find('e') == std::string::npos) {
    s += ".0";
  }
  out += s;
}

void write(std::string &out, const Value &value, int depth) {
  std::visit(
      [&](const auto &x) {
        using T = std::decay_t<decltype(x)>;
        if constexpr (std::is_same_v<T, std::monostate>) {
          out += "nil";
        } else if constexpr (std::is_same_v<T, bool>) {
          out += x ? "true" : "false";
        } else if constexpr (std::is_same_v<T, int64_t>) {
          out += std::to_string(x);
        } else if constexpr (std::is_same_v<T, double>) {
          write_float(out, x);
        } else if constexpr (std::is_same_v<T, std::string>) {
          write_string(out, x);
        } else if constexpr (std::is_same_v<T, Array>) {
          if (x.empty()) {
            out += "{}";
            return;
          }
          out += "{\n";
          for (auto &item : x) {
            indent(out, depth + 1);
            write(out, item, depth + 1);
            out += ",\n";
          }
          indent(out, depth);
          out += '}';
        } else {
          if (x.empty()) {
            out += "{}";
            return;
          }
          out += "{\n";
          for (auto &[key, item] : x) {
            indent(out, depth + 1);
            out += key;
            out += " = ";
            write(out, item, depth + 1);
            out += ",\n";
          }
          indent(out, depth);
          out += '}';
        }
      },
      value.v);
}

} // namespace

std::string print_lua(const Value &value, const std::string &header_path) {
  std::string out = "-- generated by skalder ";
  out += SKALD_VERSION;
  out += " from ";
  out += header_path;
  out += ". do not edit.\nreturn ";
  write(out, value, 0);
  out += '\n';
  return out;
}

std::string lua_literal(const SimpleRValue &value) {
  std::string out;
  std::visit([&](const auto &x) { write(out, Value(x), 0); }, value);
  return out;
}

} // namespace Skald::Emit
