-- generated by skalder 0.6.3 from test.codex. do not edit.
return {
  format_version = 1,
  skald_version = "0.6.3",
  name = "test.codex",
  globals = {
    {
      name = "age",
      type = "int",
      default = {
        t = "int",
        v = 0,
      },
    },
    {
      name = "name",
      type = "string",
      default = {
        t = "str",
        v = "",
      },
    },
    {
      name = "gender",
      type = "string",
      default = {
        t = "str",
        v = "?",
      },
    },
    {
      name = "alive",
      type = "bool",
      default = {
        t = "bool",
        v = true,
      },
    },
  },
  methods = {
    {
      name = "simple",
      ret = "action",
      args = {},
    },
    {
      name = "simple_args",
      ret = "action",
      args = {
        {
          name = "a",
          type = "int",
        },
        {
          name = "b",
          type = "string",
        },
      },
    },
    {
      name = "returns_something",
      ret = "int",
      args = {},
    },
    {
      name = "returns_w_args",
      ret = "string",
      args = {
        {
          name = "a",
          type = "int",
        },
        {
          name = "b",
          type = "string",
        },
      },
    },
  },
  modules = {
    "hold.ska",
    "test.ska",
    "test2.ska",
    "test_2.ska",
  },
}
