-- generated by skalder 0.6.3 from hold.ska. do not edit.
return {
  format_version = 1,
  skald_version = "0.6.3",
  path = "hold.ska",
  vars = {},
  testbeds = {},
  blocks = {
    {
      tag = "start",
      line = 2,
      members = {
        {
          line = 4,
          body = {
            t = "beat",
            attribution = "",
            text = {
              parts = {
                "Testing testing",
              },
            },
          },
        },
      },
    },
  },
}
