-- generated by skalder 0.6.3 from logic.ska. do not edit.
return {
  format_version = 1,
  skald_version = "0.6.3",
  path = "logic.ska",
  vars = {
    {
      name = "count",
      type = "int",
      default = {
        t = "int",
        v = 1,
      },
      line = 4,
    },
    {
      name = "other",
      type = "int",
      default = {
        t = "int",
        v = 7,
      },
      line = 5,
    },
    {
      name = "label",
      type = "string",
      default = {
        t = "str",
        v = "",
      },
      line = 6,
    },
    {
      name = "flag",
      type = "bool",
      default = {
        t = "bool",
        v = true,
      },
      line = 7,
    },
    {
      name = "ratio",
      type = "float",
      default = {
        t = "float",
        v = 0.0,
      },
      line = 8,
    },
  },
  testbeds = {},
  blocks = {
    {
      tag = "start",
      line = 11,
      members = {
        {
          line = 13,
          body = {
            t = "beat",
            attribution = "",
            text = {
              parts = {
                "Mutations with literal rvalues.",
              },
            },
          },
        },
        {
          line = 15,
          body = {
            t = "mutation",
            op = "set",
            lvalue = "count",
            rv = {
              t = "int",
              v = 5,
            },
          },
        },
        {
          line = 16,
          body = {
            t = "mutation",
            op = "add",
            lvalue = "count",
            rv = {
              t = "int",
              v = 2,
            },
          },
        },
        {
          line = 17,
          body = {
            t = "mutation",
            op = "sub",
            lvalue = "count",
            rv = {
              t = "int",
              v = 1,
            },
          },
        },
        {
          line = 18,
          body = {
            t = "mutation",
            op = "set",
            lvalue = "label",
            rv = {
              t = "str",
              v = "hello",
            },
          },
        },
        {
          line = 19,
          body = {
            t = "mutation",
            op = "set",
            lvalue = "ratio",
            rv = {
              t = "float",
              v = 1.5,
            },
          },
        },
        {
          line = 20,
          body = {
            t = "mutation",
            op = "toggle",
            lvalue = "flag",
          },
        },
        {
          line = 22,
          body = {
            t = "beat",
            attribution = "",
            text = {
              parts = {
                "Mutations with variable and method rvalues.",
              },
            },
          },
        },
        {
          line = 24,
          body = {
            t = "mutation",
            op = "set",
            lvalue = "count",
            rv = {
              t = "var",
              name = "other",
            },
          },
        },
        {
          line = 25,
          body = {
            t = "mutation",
            op = "add",
            lvalue = "count",
            rv = {
              t = "var",
              name = "other",
            },
          },
        },
        {
          line = 26,
          body = {
            t = "mutation",
            op = "set",
            lvalue = "count",
            rv = {
              t = "call",
              method = "returns_something",
              args = {},
              line = 0,
            },
          },
        },
        {
          line = 27,
          body = {
            t = "mutation",
            op = "add",
            lvalue = "count",
            rv = {
              t = "call",
              method = "returns_something",
              args = {},
              line = 0,
            },
          },
        },
        {
          line = 28,
          body = {
            t = "mutation",
            op = "sub",
            lvalue = "count",
            rv = {
              t = "call",
              method = "returns_something",
              args = {},
              line = 0,
            },
          },
        },
        {
          line = 29,
          body = {
            t = "mutation",
            op = "set",
            lvalue = "label",
            rv = {
              t = "call",
              method = "returns_w_args",
              args = {
                {
                  t = "var",
                  name = "count",
                },
                {
                  t = "str",
                  v = "x",
                },
              },
              line = 0,
            },
          },
        },
        {
          line = 31,
          body = {
            t = "beat",
            attribution = "",
            text = {
              parts = {
                "Whitespace is optional after the prefix.",
              },
            },
          },
        },
        {
          line = 33,
          body = {
            t = "mutation",
            op = "set",
            lvalue = "count",
            rv = {
              t = "int",
              v = 3,
            },
          },
        },
        {
          line = 34,
          body = {
            t = "mutation",
            op = "add",
            lvalue = "count",
            rv = {
              t = "int",
              v = 1,
            },
          },
        },
        {
          line = 35,
          body = {
            t = "call",
            method = "simple",
            args = {},
          },
        },
        {
          line = 36,
          body = {
            t = "call",
            method = "simple",
            args = {},
          },
        },
        {
          line = 38,
          body = {
            t = "beat",
            attribution = "",
            text = {
              parts = {
                "Method operations.",
              },
            },
          },
        },
        {
          line = 40,
          body = {
            t = "call",
            method = "simple",
            args = {},
          },
        },
        {
          line = 41,
          body = {
            t = "call",
            method = "simple_args",
            args = {
              {
                t = "int",
                v = 5,
              },
              {
                t = "str",
                v = "bob",
              },
            },
          },
        },
        {
          line = 42,
          body = {
            t = "call",
            method = "simple_args",
            args = {
              {
                t = "var",
                name = "count",
              },
              {
                t = "var",
                name = "label",
              },
            },
          },
        },
        {
          line = 43,
          body = {
            t = "call",
            method = "simple",
            args = {},
          },
        },
        {
          line = 44,
          body = {
            t = "mutation",
            op = "set",
            lvalue = "count",
            rv = {
              t = "call",
              method = "returns_something",
              args = {},
              line = 0,
            },
          },
        },
        {
          line = 46,
          body = {
            t = "beat",
            attribution = "",
            text = {
              parts = {
                "Inline conditionals.",
              },
            },
          },
        },
        {
          cond = {
            type = "and",
            items = {
              {
                t = "atom",
                a = {
                  t = "call",
                  method = "returns_something",
                  args = {},
                  line = 0,
                },
                cmp = "truthy",
              },
            },
          },
          line = 48,
          body = {
            t = "beat",
            attribution = "",
            text = {
              parts = {
                "Method check.",
              },
            },
          },
        },
        {
          cond = {
            type = "and",
            items = {
              {
                t = "atom",
                a = {
                  t = "call",
                  method = "returns_something",
                  args = {},
                  line = 0,
                },
                cmp = "not_truthy",
              },
            },
          },
          line = 49,
          body = {
            t = "beat",
            attribution = "",
            text = {
              parts = {
                "Negated method check.",
              },
            },
          },
        },
        {
          cond = {
            type = "and",
            items = {
              {
                t = "atom",
                a = {
                  t = "call",
                  method = "returns_something",
                  args = {},
                  line = 0,
                },
                cmp = "truthy",
              },
              {
                t = "atom",
                a = {
                  t = "var",
                  name = "flag",
                },
                cmp = "truthy",
              },
            },
          },
          line = 50,
          body = {
            t = "beat",
            attribution = "",
            text = {
              parts = {
                "Method and variable.",
              },
            },
          },
        },
        {
          cond = {
            type = "or",
            items = {
              {
                t = "atom",
                a = {
                  t = "var",
                  name = "flag",
                },
                cmp = "truthy",
              },
              {
                t = "atom",
                a = {
                  t = "call",
                  method = "returns_something",
                  args = {},
                  line = 0,
                },
                cmp = "truthy",
              },
            },
          },
          line = 51,
          body = {
            t = "beat",
            attribution = "",
            text = {
              parts = {
                "Variable or method.",
              },
            },
          },
        },
        {
          cond = {
            type = "and",
            items = {
              {
                t = "atom",
                a = {
                  t = "call",
                  method = "returns_something",
                  args = {},
                  line = 0,
                },
                cmp = "gt",
                b = {
                  t = "int",
                  v = 3,
                },
              },
            },
          },
          line = 52,
          body = {
            t = "beat",
            attribution = "",
            text = {
              parts = {
                "Method compare.",
              },
            },
          },
        },
        {
          cond = {
            type = "and",
            items = {
              {
                t = "atom",
                a = {
                  t = "var",
                  name = "count",
                },
                cmp = "eq",
                b = {
                  t = "call",
                  method = "returns_something",
                  args = {},
                  line = 0,
                },
              },
            },
          },
          line = 53,
          body = {
            t = "beat",
            attribution = "",
            text = {
              parts = {
                "Variable compare to method.",
              },
            },
          },
        },
        {
          cond = {
            type = "and",
            items = {
              {
                t = "atom",
                a = {
                  t = "call",
                  method = "returns_w_args",
                  args = {
                    {
                      t = "var",
                      name = "count",
                    },
                    {
                      t = "str",
                      v = "x",
                    },
                  },
                  line = 0,
                },
                cmp = "eq",
                b = {
                  t = "str",
                  v = "y",
                },
              },
            },
          },
          line = 54,
          body = {
            t = "beat",
            attribution = "",
            text = {
              parts = {
                "Method with args compare.",
              },
            },
          },
        },
        {
          cond = {
            type = "and",
            items = {
              {
                t = "group",
                cond = {
                  type = "and",
                  items = {
                    {
                      t = "atom",
                      a = {
                        t = "call",
                        method = "returns_something",
                        args = {},
                        line = 0,
                      },
                      cmp = "gt",
                      b = {
                        t = "int",
                        v = 1,
                      },
                    },
                  },
                },
              },
              {
                t = "atom",
                a = {
                  t = "var",
                  name = "flag",
                },
                cmp = "not_truthy",
              },
            },
          },
          line = 55,
          body = {
            t = "beat",
            attribution = "",
            text = {
              parts = {
                "Subclause with method.",
              },
            },
          },
        },
        {
          cond = {
            type = "and",
            items = {
              {
                t = "atom",
                a = {
                  t = "call",
                  method = "returns_something",
                  args = {},
                  line = 0,
                },
                cmp = "truthy",
              },
            },
          },
          line = 56,
          body = {
            t = "call",
            method = "simple",
            args = {},
          },
        },
        {
          cond = {
            type = "and",
            items = {
              {
                t = "atom",
                a = {
                  t = "var",
                  name = "flag",
                },
                cmp = "truthy",
              },
            },
          },
          line = 57,
          body = {
            t = "mutation",
            op = "set",
            lvalue = "count",
            rv = {
              t = "call",
              method = "returns_something",
              args = {},
              line = 0,
            },
          },
        },
        {
          line = 59,
          body = {
            t = "beat",
            attribution = "",
            text = {
              parts = {
                "Injected ",
                {
                  t = "insert",
                  rv = {
                    t = "call",
                    method = "returns_something",
                    args = {},
                    line = 0,
                  },
                },
                " and ",
                {
                  t = "insert",
                  rv = {
                    t = "call",
                    method = "returns_w_args",
                    args = {
                      {
                        t = "int",
                        v = 1,
                      },
                      {
                        t = "str",
                        v = "a",
                      },
                    },
                    line = 0,
                  },
                },
                ".",
              },
            },
          },
        },
        {
          t = "choices",
          line = 61,
          choices = {
            {
              cond = {
                type = "and",
                items = {
                  {
                    t = "atom",
                    a = {
                      t = "call",
                      method = "returns_something",
                      args = {},
                      line = 0,
                    },
                    cmp = "truthy",
                  },
                },
              },
              text = {
                parts = {
                  "Conditional choice",
                },
              },
              members = {
                {
                  line = 62,
                  body = {
                    t = "call",
                    method = "simple",
                    args = {},
                  },
                },
                {
                  line = 63,
                  body = {
                    t = "mutation",
                    op = "set",
                    lvalue = "count",
                    rv = {
                      t = "call",
                      method = "returns_something",
                      args = {},
                      line = 0,
                    },
                  },
                },
              },
              line = 61,
            },
            {
              text = {
                parts = {
                  "Plain choice",
                },
              },
              members = {
                {
                  line = 65,
                  body = {
                    t = "mutation",
                    op = "add",
                    lvalue = "count",
                    rv = {
                      t = "int",
                      v = 1,
                    },
                  },
                },
              },
              line = 64,
            },
          },
        },
        {
          t = "chain",
          blocks = {
            {
              cond = {
                type = "and",
                items = {
                  {
                    t = "atom",
                    a = {
                      t = "call",
                      method = "returns_something",
                      args = {},
                      line = 0,
                    },
                    cmp = "truthy",
                  },
                },
              },
              line = 67,
              members = {
                {
                  line = 69,
                  body = {
                    t = "beat",
                    attribution = "",
                    text = {
                      parts = {
                        "If on method.",
                      },
                    },
                  },
                },
              },
            },
            {
              cond = {
                type = "and",
                items = {
                  {
                    t = "atom",
                    a = {
                      t = "call",
                      method = "returns_w_args",
                      args = {
                        {
                          t = "var",
                          name = "count",
                        },
                        {
                          t = "str",
                          v = "z",
                        },
                      },
                      line = 0,
                    },
                    cmp = "eq",
                    b = {
                      t = "str",
                      v = "z",
                    },
                  },
                },
              },
              line = 71,
              members = {
                {
                  line = 73,
                  body = {
                    t = "beat",
                    attribution = "",
                    text = {
                      parts = {
                        "Elseif on method with args.",
                      },
                    },
                  },
                },
              },
            },
            {
              cond = {
                type = "and",
                items = {
                  {
                    t = "atom",
                    a = {
                      t = "call",
                      method = "returns_something",
                      args = {},
                      line = 0,
                    },
                    cmp = "not_truthy",
                  },
                  {
                    t = "atom",
                    a = {
                      t = "var",
                      name = "flag",
                    },
                    cmp = "truthy",
                  },
                },
              },
              line = 75,
              members = {
                {
                  line = 77,
                  body = {
                    t = "beat",
                    attribution = "",
                    text = {
                      parts = {
                        "Elseif negated method and variable.",
                      },
                    },
                  },
                },
              },
            },
            {
              line = 79,
              members = {
                {
                  line = 81,
                  body = {
                    t = "beat",
                    attribution = "",
                    text = {
                      parts = {
                        "Else.",
                      },
                    },
                  },
                },
              },
            },
          },
        },
        {
          line = 85,
          body = {
            t = "exit",
          },
        },
      },
    },
  },
}
