-- generated by skalder 0.6.3 from test.ska. do not edit.
return {
  format_version = 1,
  skald_version = "0.6.3",
  path = "test.ska",
  vars = {},
  testbeds = {},
  blocks = {
    {
      tag = "start",
      line = 1,
      members = {
        {
          line = 3,
          body = {
            t = "beat",
            attribution = "",
            text = {
              parts = {
                "First we test the exit:",
              },
            },
          },
        },
        {
          line = 5,
          body = {
            t = "beat",
            attribution = "",
            text = {
              parts = {
                "And then we test a special sub beat",
              },
            },
          },
        },
        {
          line = 7,
          body = {
            t = "beat",
            attribution = "",
            text = {
              parts = {
                "Wait, let's go!",
              },
            },
          },
        },
        {
          line = 9,
          body = {
            t = "go",
            module = "test2.ska",
            start_in = "",
          },
        },
        {
          line = 11,
          body = {
            t = "beat",
            attribution = "",
            text = {
              parts = {
                "And we're out?",
              },
            },
          },
        },
        {
          line = 13,
          body = {
            t = "beat",
            attribution = "",
            text = {
              parts = {
                "And then we go:",
              },
            },
          },
        },
        {
          line = 15,
          body = {
            t = "exit",
          },
        },
      },
    },
  },
}
