-- generated by skalder 0.6.3 from test_2.ska. do not edit.
return {
  format_version = 1,
  skald_version = "0.6.3",
  path = "test_2.ska",
  vars = {
    {
      name = "age",
      type = "int",
      default = {
        t = "int",
        v = 30,
      },
      line = 2,
    },
    {
      name = "name",
      type = "string",
      default = {
        t = "str",
        v = "",
      },
      line = 3,
    },
    {
      name = "gender",
      type = "string",
      default = {
        t = "str",
        v = "f",
      },
      line = 4,
    },
    {
      name = "alive",
      type = "bool",
      default = {
        t = "bool",
        v = true,
      },
      line = 5,
    },
    {
      name = "progress",
      type = "float",
      default = {
        t = "float",
        v = 0.0,
      },
      line = 6,
    },
  },
  testbeds = {
    {
      name = "alpha",
      line = 9,
      sets = {
        {
          var = "age",
          value = {
            t = "int",
            v = 50,
          },
          line = 10,
        },
        {
          var = "name",
          value = {
            t = "str",
            v = "Bob",
          },
          line = 11,
        },
        {
          var = "gender",
          value = {
            t = "str",
            v = "m",
          },
          line = 12,
        },
      },
    },
  },
  blocks = {
    {
      tag = "start",
      line = 15,
      members = {
        {
          line = 17,
          body = {
            t = "beat",
            attribution = "",
            text = {
              parts = {
                "This is the first beat. My age is ",
                {
                  t = "insert",
                  rv = {
                    t = "var",
                    name = "age",
                  },
                },
                ". Now we mutate ...",
              },
            },
          },
        },
        {
          t = "choices",
          line = 19,
          choices = {
            {
              text = {
                parts = {
                  "Loop",
                },
              },
              members = {
                {
                  line = 20,
                  body = {
                    t = "move",
                    target = "start",
                  },
                },
              },
              line = 19,
            },
            {
              text = {
                parts = {
                  "Continue",
                },
              },
              members = {},
              line = 21,
            },
          },
        },
        {
          line = 23,
          body = {
            t = "mutation",
            op = "add",
            lvalue = "age",
            rv = {
              t = "int",
              v = 1,
            },
          },
        },
        {
          line = 25,
          body = {
            t = "beat",
            attribution = "",
            text = {
              parts = {
                "A mutation should have just happened, and age is now ",
                {
                  t = "insert",
                  rv = {
                    t = "var",
                    name = "age",
                  },
                },
                ".",
              },
            },
          },
        },
        {
          t = "chain",
          blocks = {
            {
              cond = {
                type = "and",
                items = {
                  {
                    t = "atom",
                    a = {
                      t = "var",
                      name = "age",
                    },
                    cmp = "gt",
                    b = {
                      t = "int",
                      v = 30,
                    },
                  },
                },
              },
              line = 27,
              members = {
                {
                  line = 29,
                  body = {
                    t = "beat",
                    attribution = "",
                    text = {
                      parts = {
                        "I'm over 30!",
                      },
                    },
                  },
                },
              },
            },
            {
              cond = {
                type = "and",
                items = {
                  {
                    t = "atom",
                    a = {
                      t = "var",
                      name = "age",
                    },
                    cmp = "gt",
                    b = {
                      t = "int",
                      v = 10,
                    },
                  },
                },
              },
              line = 31,
              members = {
                {
                  line = 33,
                  body = {
                    t = "beat",
                    attribution = "",
                    text = {
                      parts = {
                        "I'm over 10!",
                      },
                    },
                  },
                },
                {
                  line = 35,
                  body = {
                    t = "beat",
                    attribution = "",
                    text = {
                      parts = {
                        "Like really though, over ten.",
                      },
                    },
                  },
                },
                {
                  line = 37,
                  body = {
                    t = "call",
                    method = "simple",
                    args = {},
                  },
                },
                {
                  line = 39,
                  body = {
                    t = "mutation",
                    op = "add",
                    lvalue = "age",
                    rv = {
                      t = "int",
                      v = 10,
                    },
                  },
                },
                {
                  line = 41,
                  body = {
                    t = "beat",
                    attribution = "",
                    text = {
                      parts = {
                        "And that's it for the rest of that stuff.",
                      },
                    },
                  },
                },
              },
            },
            {
              line = 43,
              members = {
                {
                  line = 45,
                  body = {
                    t = "beat",
                    attribution = "",
                    text = {
                      parts = {
                        "I'm 10 or under!",
                      },
                    },
                  },
                },
              },
            },
          },
        },
        {
          line = 49,
          body = {
            t = "beat",
            attribution = "",
            text = {
              parts = {
                "Coming out of the cond my age is ",
                {
                  t = "insert",
                  rv = {
                    t = "var",
                    name = "age",
                  },
                },
                ".",
              },
            },
          },
        },
        {
          line = 51,
          body = {
            t = "mutation",
            op = "add",
            lvalue = "age",
            rv = {
              t = "int",
              v = 1,
            },
          },
        },
        {
          line = 53,
          body = {
            t = "beat",
            attribution = "",
            text = {
              parts = {
                "Another year! Now my age is ",
                {
                  t = "insert",
                  rv = {
                    t = "var",
                    name = "age",
                  },
                },
                ".",
              },
            },
          },
        },
        {
          t = "choices",
          line = 55,
          choices = {
            {
              text = {
                parts = {
                  "Again!",
                },
              },
              members = {
                {
                  line = 56,
                  body = {
                    t = "move",
                    target = "start",
                  },
                },
              },
              line = 55,
            },
            {
              text = {
                parts = {
                  "Bye",
                },
              },
              members = {},
              line = 57,
            },
          },
        },
        {
          line = 59,
          body = {
            t = "call",
            method = "simple_args",
            args = {
              {
                t = "int",
                v = 5,
              },
              {
                t = "str",
                v = "bob",
              },
            },
          },
        },
        {
          cond = {
            type = "and",
            items = {
              {
                t = "atom",
                a = {
                  t = "var",
                  name = "gender",
                },
                cmp = "eq",
                b = {
                  t = "str",
                  v = "m",
                },
              },
            },
          },
          line = 61,
          body = {
            t = "mutation",
            op = "add",
            lvalue = "age",
            rv = {
              t = "int",
              v = 2,
            },
          },
        },
        {
          line = 64,
          body = {
            t = "beat",
            attribution = "tester",
            text = {
              parts = {
                "This is an attributed beat.",
              },
            },
          },
        },
        {
          t = "choices",
          line = 66,
          choices = {
            {
              text = {
                parts = {
                  "This choice will continue",
                },
              },
              members = {},
              line = 66,
            },
            {
              text = {
                parts = {
                  "Goes to grandchild b",
                },
              },
              members = {
                {
                  line = 68,
                  body = {
                    t = "move",
                    target = "start.alice.b",
                  },
                },
              },
              line = 67,
            },
            {
              text = {
                parts = {
                  "Goes to child2",
                },
              },
              members = {
                {
                  line = 70,
                  body = {
                    t = "move",
                    target = "start.bob",
                  },
                },
              },
              line = 69,
            },
          },
        },
        {
          line = 72,
          body = {
            t = "beat",
            attribution = "",
            text = {
              parts = {
                "This is the continuation beat.",
              },
            },
          },
        },
      },
    },
    {
      tag = "start.alice",
      line = 74,
      members = {
        {
          line = 76,
          body = {
            t = "beat",
            attribution = "",
            text = {
              parts = {
                "This is first child block. And here we do some conditionals:",
              },
            },
          },
        },
        {
          line = 78,
          body = {
            t = "beat",
            attribution = "",
            text = {
              parts = {
                "This comes after the conditional blocks.",
              },
            },
          },
        },
      },
    },
    {
      tag = "start.alice.a",
      line = 80,
      members = {
        {
          line = 82,
          body = {
            t = "beat",
            attribution = "",
            text = {
              parts = {
                "This is grandchild a",
              },
            },
          },
        },
        {
          t = "choices",
          line = 84,
          choices = {
            {
              text = {
                parts = {
                  "Up to parent",
                },
              },
              members = {
                {
                  line = 85,
                  body = {
                    t = "move",
                    target = "start",
                  },
                },
              },
              line = 84,
            },
            {
              text = {
                parts = {
                  "To sib",
                },
              },
              members = {
                {
                  line = 87,
                  body = {
                    t = "move",
                    target = "start.alice.b",
                  },
                },
              },
              line = 86,
            },
          },
        },
      },
    },
    {
      tag = "start.alice.b",
      line = 89,
      members = {
        {
          line = 91,
          body = {
            t = "beat",
            attribution = "",
            text = {
              parts = {
                "This is grandchild b",
              },
            },
          },
        },
      },
    },
    {
      tag = "start.bob",
      line = 93,
      members = {
        {
          line = 95,
          body = {
            t = "beat",
            attribution = "",
            text = {
              parts = {
                "This is second child block",
              },
            },
          },
        },
        {
          line = 97,
          body = {
            t = "beat",
            attribution = "",
            text = {
              parts = {
                "And this is the end.",
              },
            },
          },
        },
        {
          line = 99,
          body = {
            t = "exit",
          },
        },
      },
    },
  },
}
