-- generated by skalder 0.6.3 from test2.ska. do not edit.
return {
  format_version = 1,
  skald_version = "0.6.3",
  path = "test2.ska",
  vars = {},
  testbeds = {},
  blocks = {
    {
      tag = "start",
      line = 1,
      members = {
        {
          line = 3,
          body = {
            t = "beat",
            attribution = "",
            text = {
              parts = {
                "We got here from regular test! Woohoo!",
              },
            },
          },
        },
        {
          line = 5,
          body = {
            t = "beat",
            attribution = "",
            text = {
              parts = {
                "And now we exit:",
              },
            },
          },
        },
        {
          line = 7,
          body = {
            t = "exit",
          },
        },
      },
    },
  },
}
